version: "3"
services:
  apache:
    image: polinavngrd/apache:latest
    container_name: apache_container
    ports:
      - 8080:8080
    networks:
      - task17

  nginx:
    image: polinavngrd/nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
      - 443:443
    networks:
      - task17

networks:
  task17:
